engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  dogma:
    enabled: true

ratings:
  paths:
    - angular/**
    - "**.js"

languages:
  JavaScript: true
  Ruby: false
  PHP: true
  Python: false

exclude_paths:
- "gulpfile.js"
- "public/js/vendor.js"
- "public/dist/js/app.js"
- "tasks/**"
- "tests/**"
